//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHoaDon
    {
        public int mahd { get; set; }
        public int masp { get; set; }
        public Nullable<int> mam { get; set; }
        public Nullable<int> mas { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> dongia { get; set; }
    
        public virtual CTSanPham CTSanPham { get; set; }
    }
}
