//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTSanPham
    {
        public CTSanPham()
        {
            this.CTHoaDon = new HashSet<CTHoaDon>();
        }
    
        public int masp { get; set; }
        public int mam { get; set; }
        public string link { get; set; }
        public Nullable<decimal> dongia { get; set; }
        public Nullable<int> soluong { get; set; }
        public int mas { get; set; }
    
        public virtual mau mau { get; set; }
        public virtual size size { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual ICollection<CTHoaDon> CTHoaDon { get; set; }
    }
}
