//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiamGia
    {
        public GiamGia()
        {
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public int magg { get; set; }
        public Nullable<int> mucgiam { get; set; }
        public Nullable<System.DateTime> ngaybd { get; set; }
        public Nullable<System.DateTime> ngaykt { get; set; }
    
        public virtual ICollection<HoaDon> HoaDon { get; set; }
    }
}
