//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int mahd { get; set; }
        public int matk { get; set; }
        public Nullable<int> magg { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public string diachigiaohang { get; set; }
        public string tinhtrang { get; set; }
        public Nullable<bool> dathanhtoan { get; set; }
    
        public virtual GiamGia GiamGia { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
