//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class mau
    {
        public mau()
        {
            this.CTSanPham = new HashSet<CTSanPham>();
        }
    
        public int mam { get; set; }
        public string tenm { get; set; }
    
        public virtual ICollection<CTSanPham> CTSanPham { get; set; }
    }
}
