//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class G6_QLBQAEntities : DbContext
    {
        public G6_QLBQAEntities()
            : base("name=G6_QLBQAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BinhLuan> BinhLuan { get; set; }
        public DbSet<CTSanPham> CTSanPham { get; set; }
        public DbSet<CTHoaDon> CTHoaDon { get; set; }
        public DbSet<DanhMuc> DanhMuc { get; set; }
        public DbSet<GiamGia> GiamGia { get; set; }
        public DbSet<HoaDon> HoaDon { get; set; }
        public DbSet<LoaiSp> LoaiSp { get; set; }
        public DbSet<mau> mau { get; set; }
        public DbSet<NhaCungCap> NhaCungCap { get; set; }
        public DbSet<Quyen> Quyen { get; set; }
        public DbSet<SanPham> SanPham { get; set; }
        public DbSet<size> size { get; set; }
        public DbSet<TaiKhoan> TaiKhoan { get; set; }
        public DbSet<ThuongHieu> ThuongHieu { get; set; }
    }
}
