//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public NhaCungCap()
        {
            this.SanPham = new HashSet<SanPham>();
        }
    
        public int mancc { get; set; }
        public string tenncc { get; set; }
        public string email { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
    
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
