//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quyen
    {
        public Quyen()
        {
            this.TaiKhoan = new HashSet<TaiKhoan>();
        }
    
        public int maquyen { get; set; }
        public string tenquyen { get; set; }
    
        public virtual ICollection<TaiKhoan> TaiKhoan { get; set; }
    }
}
