//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.CTSanPham = new HashSet<CTSanPham>();
        }
    
        public int masp { get; set; }
        public string tensp { get; set; }
        public decimal giaban { get; set; }
        public string mota { get; set; }
        public int soluong { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public string anhchinh { get; set; }
        public Nullable<int> math { get; set; }
        public Nullable<int> maloai { get; set; }
        public Nullable<int> madm { get; set; }
        public Nullable<int> mancc { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        public virtual ICollection<CTSanPham> CTSanPham { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual LoaiSp LoaiSp { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
