//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public int matk { get; set; }
        public string tenkh { get; set; }
        public string gioitinh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string email { get; set; }
        public string matkhau { get; set; }
        public string anhdaidien { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public Nullable<int> maquyen { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        public virtual ICollection<HoaDon> HoaDon { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
