//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuongHieu
    {
        public ThuongHieu()
        {
            this.SanPham = new HashSet<SanPham>();
        }
    
        public int math { get; set; }
        public string tenth { get; set; }
    
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
